USE [Backoffice]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ENDERECO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[CEP] [varchar](10) NOT NULL,
	[LOGRADOURO] [varchar](150) NOT NULL,
	[NUMERO] [varchar](10) NULL,
	[COMPLEMENTO] [varchar](100) NULL,
	[BAIRRO] [varchar](50) NOT NULL,
	[CIDADE] [varchar](50) NOT NULL,
	[ESTADO] [varchar](50) NOT NULL,
	[PAIS] [varchar](30) NOT NULL,
 CONSTRAINT [PK_ENDERECO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO