USE [Backoffice]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_INDICACAO] [int] NOT NULL,
	[NOME_COMPLETO] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[TELEFONE] [varchar](15) NULL,
	[CELULAR] [varchar](15) NULL,
	[DATA_NASCIMENTO] [date] NOT NULL,
	[RG] [varchar](20) NULL,
	[ORGAO_EMISSOR_RG] [varchar](10) NULL,
	[SEXO] [char](1) NULL,
	[ESTADO_CIVIL] [varchar](10) NULL,
	[NOME_MAE] [varchar](100) NULL,
	[LOGIN] [varchar](100) NOT NULL,
	[SENHA] [varchar](255) NOT NULL,
	[SENHA_FINANCEIRA] [varchar](255) NOT NULL
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO