USE `BACKOFFICE`;
 
CREATE TABLE BONUS_IND_INDIRETA (
	ID INT AUTO_INCREMENT NOT NULL,
    ID_USUARIO_BONUS INT,
	VALOR_BONUS DECIMAL(10,2),
	ID_USUARIO_GERADOR INT,
	FL_PGTO_CONFIRMADO CHAR(1),
	CONSTRAINT PK_BONUS_IND_INDIR PRIMARY KEY (`ID` ASC) 
);