USE `BACKOFFICE`;

DELIMITER $

CREATE TRIGGER TR_BONUS_INDICACAO AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BONUS_IND_DIRETA (ID_USUARIO_BONUS, VALOR_BONUS, ID_USUARIO_GERADOR, FL_PGTO_CONFIRMADO)
	SELECT NEW.ID_INDICACAO, (PL_USUARIO.VALOR_PLANO * (PL_PAI.PERCENTUAL_IND_DIRETA/100)), NEW.ID, NULL 
    FROM USUARIO AS USU_PAI 
    INNER JOIN PLANOS AS PL_PAI ON PL_PAI.ID_PLANO = USU_PAI.ID_PLANO 
    INNER JOIN PLANOS AS PL_USUARIO ON PL_USUARIO.ID_PLANO = NEW.ID_PLANO
    WHERE USU_PAI.ID = NEW.ID_INDICACAO;
END; 
$

-- DROP TRIGGER TR_BONUS_INDICACAO;
-- SELECT 
--      trigger_name, 
--      action_order
--  FROM
--      information_schema.triggers
--  WHERE
--      trigger_schema = 'backoffice'
--  ORDER BY 
--      event_object_table , 
--      action_timing , 
--      event_manipulation;