DELIMITER $

CREATE PROCEDURE RETORNA_REDE_POR_GERACAO (p_GERACAO INT, p_ID_USUARIO INT)
BEGIN
	DECLARE v_GERACAO_AUX INT DEFAULT 1;
    DECLARE V_CONNID INT;
    DECLARE NOMETABELA VARCHAR(20);
    
	SELECT CONNECTION_ID() INTO V_CONNID;
		
	SET NOMETABELA = 'TMP_USUARIO_GERACAO';
	SET @SQLTEXT = CONCAT('CREATE TABLE ',NOMETABELA,V_CONNID,'(ID_USUARIO INT, GERACAO INT)');
	PREPARE stmt from @SQLTEXT;
	EXECUTE stmt;

	SET @SQLTEXT = CONCAT('INSERT INTO ',NOMETABELA,V_CONNID, ' SELECT ID, 1 FROM USUARIO WHERE ID_INDICACAO = ',p_ID_USUARIO);
	PREPARE stmt from @SQLTEXT;
	EXECUTE stmt;

	WHILE p_GERACAO > v_GERACAO_AUX
	DO
		SET @SQLTEXT = CONCAT('INSERT INTO ',NOMETABELA,V_CONNID,' (ID_USUARIO, GERACAO) SELECT ID, ',v_GERACAO_AUX + 1 ,' FROM USUARIO ', 'WHERE ID_INDICACAO IN (SELECT ID_USUARIO FROM ',NOMETABELA,V_CONNID,' WHERE GERACAO = ',v_GERACAO_AUX, ')');
		PREPARE stmt from @SQLTEXT;
		EXECUTE stmt;

		SET v_GERACAO_AUX = v_GERACAO_AUX + 1;
	END WHILE;
    
	-- SET @SQLTEXT = CONCAT('SELECT * FROM ',NOMETABELA,V_CONNID, ' WHERE GERACAO = ',p_GERACAO);
    SET @SQLTEXT = CONCAT('SELECT U.ID, U.NOME_COMPLETO, U.EMAIL, U.CELULAR, U.DATA_NASCIMENTO, U.CPF, U.ID_PLANO, P.GERACAO Geracao FROM USUARIO AS U INNER JOIN ',NOMETABELA,V_CONNID, ' AS P ON U.ID = P.ID_USUARIO WHERE P.GERACAO = ',p_GERACAO);
	PREPARE stmt from @SQLTEXT;
	EXECUTE stmt;
		 
	SET @SQLTEXT = CONCAT('DROP TABLE ',NOMETABELA,V_CONNID);
	PREPARE stmt from @SQLTEXT;
	EXECUTE stmt;

END;
$
DELIMITER ;

-- CALL RETORNA_REDE_POR_GERACAO (3,1)

