USE `BACKOFFICE`;
 
CREATE TABLE PLANOS (
	ID_PLANO INT AUTO_INCREMENT NOT NULL,
	DESCRICAO VARCHAR(15),
	VALOR_PLANO DECIMAL(10,2),
	PERCENTUAL_IND_DIRETA DECIMAL(10,2),
	NIVEL_IND_INDIRETA INT,
	NIVEL_BONUS_RESIDUAL INT,
	PERCENTUAL_BONUS_RENOVACAO DECIMAL(10,2),
	PERCENTUAL_BONUS_VENDA DECIMAL(10,2),
	NIVEL_BONUS_UNILEVEL INT,
	CARREIRA CHAR(1) ,
CONSTRAINT PK_PLANO PRIMARY KEY (`ID_PLANO` ASC) 
);

/* POPULAR TABELA COM INFO DOS PLANOS*/
INSERT INTO PLANOS
SELECT 1, 'FREE', 0, 10, 2, 2, 10, 10, NULL, 'N' 
UNION ALL
SELECT 2, 'START', 100, 20, 3, 3, 20, 15, 3, 'S' 
UNION ALL
SELECT 3, 'PREMIUM', 300, 30, 4, 4, 30, 20, 4, 'S' 
UNION ALL
SELECT 4, 'TOP', 600, 50, 5, 5, 50, 25, 5, 'S' 